# install firstly color schemes from here: https://github.com/alacritty/alacritty-theme?tab=readme-ov-file

import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.5

[window.padding]
x = 0
y = 0
